apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: eurytus.com
      http:
        paths:
          - path: /api/v1/users/?(.*)
            backend:
              serviceName: auth-cluster-srv
              servicePort: 4000
          - path: /api/v1/challenges/?(.*)
            backend:
              serviceName: challenges-cluster-srv
              servicePort: 4000
          - path: /api/v1/moderate/?(.*)
            backend:
              serviceName: moderate-challenges-cluster-srv
              servicePort: 4000
          - path: /api/v1/compile/?(.*)
            backend:
              serviceName: execute-challenges-cluster-srv
              servicePort: 4000
          - path: /api/v1/history/?(.*)
            backend:
              serviceName: history-cluster-srv
              servicePort: 4000
          - path: /
            backend:
              serviceName: eurytus-ui-cluster-srv
              servicePort: 3000